<a href="https://colab.research.google.com/github/Radityaz/2025_AI_TI1B/blob/main/Riko_AI_Jobsheet02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jobsheet 02 | OPERASI MATEMATIKA, VEKTOR, MATRIKS DAN TIPE DATA

## Tugas Praktikum 1

a. A x B

In [1]:
import numpy as np

# Definisi matriks
A = np.array([[3, 1], [2, 0]])
B = np.array([[2, 1], [1, -1]])

# Perkalian matriks A x B
AxB = np.matmul(A, B)

# Menampilkan hasil
print("A x B:")
print(AxB)

A x B:
[[7 2]
 [4 2]]


b. B x C

In [2]:
import numpy as np

# Definisi matriks
B = np.array([[2, 1], [1, -1]])
C = np.array([[-1, 1, 2], [2, 0, -1]])

# Perkalian matriks B x C
BxC = np.matmul(B, C)

# Menampilkan hasil
print("B x C:")
print(BxC)

B x C:
[[ 0  2  3]
 [-3  1  3]]


## Tugas Praktikum 2

a. 6!

In [3]:
import math

faktorial_6 = math.factorial(6)
print("6! =", faktorial_6)

6! = 720


b. 8! / 5!

In [4]:
import math

faktorial_8_5 = math.factorial(8) / math.factorial(5)

print("8! / 5! =", faktorial_8_5)

8! / 5! = 336.0


##Tugas Praktikum 3

In [6]:
import numpy as np

# Definisi vektor
A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

# Panjang masing-masing vektor (magnitude)
magnitude_A = np.linalg.norm(A)
magnitude_B = np.linalg.norm(B)

# Perkalian titik (dot product)
dot_product = np.dot(A, B)

# Perkalian silang (cross product)
cross_product = np.cross(A, B)

print("Panjang vektor A:", magnitude_A)
print("Panjang vektor B:", magnitude_B)
print("Perkalian titik A . B:", dot_product)
print("Perkalian silang A x B:")
print(cross_product)


Panjang vektor A: 9.1104335791443
Panjang vektor B: 12.409673645990857
Perkalian titik A . B: 58
Perkalian silang A x B:
[ 24  79 -51]
